### ISSUE TITLE
An unhandled error occurred inside electron-rebuild, node-gyp failed to rebuild

### ISSUE THREAD

**Issue by abbaty48** [agracio/electron-edge-js#140]
I am using **electron-forge** and **react** everything works fine, until i install this package: **electron-edge-js**. i try running **npm start** but not working.
I am using 
  -Ubuntu 22.04
  -Npm 8.12.2
  -node v16.15.0
  - electron-cgi: "^1.0.6",
  - electron: "^20.0.2",
  - "@electron-forge/cli": "^6.0.0-beta.65",
    "@electron-forge/maker-deb": "^6.0.0-beta.65",
    "@electron-forge/maker-rpm": "^6.0.0-beta.65",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.65",
    "@electron-forge/maker-zip": "^6.0.0-beta.65",
    "@electron-forge/plugin-webpack": "^6.0.0-beta.65",

package.json script:
   "start": "electron-forge start",

This is the error when run **npm start**

```
> npm start

> create-electron-ts-react@3.1.14 start
> electron-forge start && build:tailwind

✔ Checking your system
✔ Locating Application
⠴ Preparing native dependencies: 0 / 1make: Entering directory '/home/abbatyya/Documents/IProjects/LEARNING/SOFTWAREAPP/ELECTRON/erts/node_modules/electron-edge-js/build'
  TOUCH Release/obj.target/edge_nativeclr.stamp
  CXX(target) Release/obj.target/edge_coreclr/src/common/v8synchronizationcontext.o
⠸ Preparing native dependencies: 0 / 1In file included from ../../nan/nan.h:180,
                 from ../src/common/edge_common.h:8,
                 from ../src/common/v8synchronizationcontext.cpp:17:
../../nan/nan_callbacks.h:55:23: error: ‘AccessorSignature’ is not a member of ‘v8’
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                       ^~~~~~~~~~~~~~~~~
../../nan/nan_callbacks.h:55:40: error: template argument 1 is invalid
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                                        ^
In file included from ../src/common/edge_common.h:8,
                 from ../src/common/v8synchronizationcontext.cpp:17:
../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:
../../nan/nan.h:2546:19: error: no matching function for call to ‘v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&, Nan::imp::Sig&)’
 2546 |   tpl->SetAccessor(
      |   ~~~~~~~~~~~~~~~~^
 2547 |       name
      |       ~~~~         
 2548 |     , getter_
      |     ~~~~~~~~~      
 2549 |     , setter_
      |     ~~~~~~~~~      
 2550 |     , obj
      |     ~~~~~          
 2551 |     , settings
      |     ~~~~~~~~~~     
 2552 |     , attribute
      |     ~~~~~~~~~~~    
 2553 | #if (NODE_MODULE_VERSION < NODE_18_0_MODULE_VERSION)
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2554 |     , signature
      |     ~~~~~~~~~~~    
 2555 | #endif
      | ~~~~~~             
 2556 |   );
      |   ~                
In file included from /home/abbatyya/.electron-gyp/20.0.2/include/node/v8-function.h:15,
                 from /home/abbatyya/.electron-gyp/20.0.2/include/node/v8.h:33,
                 from ../src/common/edge_common.h:4,
                 from ../src/common/v8synchronizationcontext.cpp:17:
/home/abbatyya/.electron-gyp/20.0.2/include/node/v8-template.h:807:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
  807 |   void SetAccessor(
      |        ^~~~~~~~~~~
/home/abbatyya/.electron-gyp/20.0.2/include/node/v8-template.h:812:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
  812 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
      |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/abbatyya/.electron-gyp/20.0.2/include/node/v8-template.h:814:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
  814 |   void SetAccessor(
      |        ^~~~~~~~~~~
/home/abbatyya/.electron-gyp/20.0.2/include/node/v8-template.h:819:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
  819 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
      |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/common/v8synchronizationcontext.cpp: In static member function ‘static void V8SynchronizationContext::Initialize()’:
../src/common/v8synchronizationcontext.cpp:43:90: warning: cast between incompatible function types from ‘void (*)(uv_async_t*, int)’ {aka ‘void (*)(uv_async_s*, int)’} to ‘uv_async_cb’ {aka ‘void (*)(uv_async_s*)’} [-Wcast-function-type]
   43 |     uv_async_init(uv_default_loop(), &V8SynchronizationContext::uv_edge_async->uv_async, (uv_async_cb)continueOnV8Thread);
      |                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/common/v8synchronizationcontext.cpp: In static member function ‘static uv_edge_async_t* V8SynchronizationContext::RegisterAction(uv_async_edge_cb, void*)’:
../src/common/v8synchronizationcontext.cpp:69:68: warning: cast between incompatible function types from ‘void (*)(uv_async_t*, int)’ {aka ‘void (*)(uv_async_s*, int)’} to ‘uv_async_cb’ {aka ‘void (*)(uv_async_s*)’} [-Wcast-function-type]
   69 |         uv_async_init(uv_default_loop(), &uv_edge_async->uv_async, (uv_async_cb)continueOnV8Thread);
      |                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
⠼ Preparing native dependencies: 0 / 1At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unused-private-field’ may have been intended to silence earlier diagnostics
make: *** [edge_coreclr.target.mk:157: Release/obj.target/edge_coreclr/src/common/v8synchronizationcontext.o] Error 1
make: Leaving directory '/home/abbatyya/Documents/IProjects/LEARNING/SOFTWAREAPP/ELECTRON/erts/node_modules/electron-edge-js/build'
✖ Preparing native dependencies: 0 / 1

An unhandled error has occurred inside Forge:
node-gyp failed to rebuild '/home/abbatyya/Documents/IProjects/LEARNING/SOFTWAREAPP/ELECTRON/erts/node_modules/electron-edge-js'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2


Error: node-gyp failed to rebuild '/home/abbatyya/Documents/IProjects/LEARNING/SOFTWAREAPP/ELECTRON/erts/node_modules/electron-edge-js'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2


    at NodeGyp.rebuildModule (/home/abbatyya/Documents/IProjects/LEARNING/SOFTWAREAPP/ELECTRON/erts/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:120:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (/home/abbatyya/Documents/IProjects/LEARNING/SOFTWAREAPP/ELECTRON/erts/node_modules/electron-rebuild/lib/src/module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (/home/abbatyya/Documents/IProjects/LEARNING/SOFTWAREAPP/ELECTRON/erts/node_modules/electron-rebuild/lib/src/module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (/home/abbatyya/Documents/IProjects/LEARNING/SOFTWAREAPP/ELECTRON/erts/node_modules/electron-rebuild/lib/src/rebuild.js:149:13)
    at async Rebuilder.rebuild (/home/abbatyya/Documents/IProjects/LEARNING/SOFTWAREAPP/ELECTRON/erts/node_modules/electron-rebuild/lib/src/rebuild.js:112:17)
    at async /home/abbatyya/Documents/IProjects/LEARNING/SOFTWAREAPP/ELECTRON/erts/node_modules/@electron-forge/core/dist/util/rebuild.js:30:9
```

**Comment by abbaty48** [comment]
i have resolved the problem, i was having electron v20 instead of version 18, so i install electron v18
