### ISSUE TITLE
The specified module could not be found.(electron 4.1.0)

### ISSUE THREAD

**Issue by Veiintc** [agracio/electron-edge-js#67]
electron:4.1.0
electron-edge-js:12.4.0
It work on my computer(window 10),but when I copy the  electron app to another(window server 2012),It fails on start with the following error:

Error: The specified module could not be found.
\\?\C:\Users\Administrator\Desktop\electron app\resources\node_modules\electron-edge-js\lib\native\win32\x64\10.11.0\edge_nativeclr.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)

    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\electron app\resources\node_modules\elec
tron-edge-js\lib\edge.js:61:10)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\electron app\resources\node_modules\elec
tron-edge-js\lib\edge.js:190:3)

Does it have any special dependence?

**Comment by Zackery747** [comment]
I have the same issue :(

**Comment by Veiintc** [comment]
Add c++ vc_redist.x64.exe
