### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by caolonggang** [agracio/electron-edge-js#87]
Running on Windows 7, the 32-bit operating system has a problem

Uncaught Exception:

Error: The specified module could not be found.

?lE:printwin ja32 -unpackedlresourcesapp.asarau.nackel...ege nativeclr.nodeat process.fuhÈ [as dlopen] (electron/js2c/asar.js:140:31)

at Object.Module. extensions..node (internal/modules/cijs/loaderjs:1016:18)at Object.func [as .node] (electron/js2c/asar.js:140:31)

at Module.load (internal/modules/cjs/loader.js:816:32)

at Module. load (internal/modules/cjs/loader.js:728:14)

at Function.Module. load (electron/js2c/asar.js:748:26)

at Module.require (internal/modules/cjs/loader.js:853:19)

at require (internal/modules/cjs/helpers.js:74:18)

at Object. < anonymous »

(E:printwin-ia32-unpackedresourcesapp,asarnode moduleslelectron-edge-..:10)at Module. compile (internal/modules/cjs/loader.js:968:30)

**Comment by weishour** [comment]
Install VC_redist.x86.exe

**Comment by weishour** [comment]
@caolonggang Install VC_redist.x86.exe will solve this problem
