### ISSUE TITLE
MAC Build edge_nativeclr.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 72. 

### ISSUE THREAD

**Issue by pmahend1** [agracio/electron-edge-js#95]
I used nodejs 12.7.0 by `nvm install 12.7.0` and `nvm use 12.7.0`

```log
Mac_User_Name@Macbook Project_Folder % PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig \
npm install electron-edge-js                     

> edge-cs@1.2.1 install /Users/Mac_User_Name/Projects/GitHub/Project_Folder/node_modules/edge-cs
> node tools/install.js

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

> edge@7.10.1 install /Users/Mac_User_Name/Projects/GitHub/Project_Folder/node_modules/edge
> node tools/install.js

  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o
In file included from ../src/mono/clractioncontext.cpp:1:
../src/mono/edge.h:14:30: error: no member named 'Handle' in namespace 'v8'
MonoString* stringV82CLR(v8::Handle<v8::String> text);
                         ~~~~^
../src/mono/edge.h:14:47: error: expected '(' for function-style cast or type construction
MonoString* stringV82CLR(v8::Handle<v8::String> text);
                                    ~~~~~~~~~~^
../src/mono/edge.h:14:49: error: use of undeclared identifier 'text'; did you mean 'exit'?
MonoString* stringV82CLR(v8::Handle<v8::String> text);
                                                ^~~~
                                                exit
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:145:7: note: 'exit' declared here
void     exit(int) __dead2;
         ^
In file included from ../src/mono/clractioncontext.cpp:1:
../src/mono/edge.h:15:39: error: no member named 'Handle' in namespace 'v8'
MonoString* exceptionV82stringCLR(v8::Handle<v8::Value> exception);
                                  ~~~~^
../src/mono/edge.h:15:55: error: expected '(' for function-style cast or type construction
MonoString* exceptionV82stringCLR(v8::Handle<v8::Value> exception);
                                             ~~~~~~~~~^
../src/mono/edge.h:15:57: error: use of undeclared identifier 'exception'
MonoString* exceptionV82stringCLR(v8::Handle<v8::Value> exception);
                                                        ^
6 errors generated.
make: *** [Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Mac_User_Name/.nvm/versions/node/v12.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:266:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/Mac_User_Name/.nvm/versions/node/v12.7.0/bin/node" "/Users/Mac_User_Name/.nvm/versions/node/v12.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/Mac_User_Name/Projects/GitHub/Project_Folder/node_modules/edge
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> electron-edge-js@12.14.2 install /Users/Mac_User_Name/Projects/GitHub/Project_Folder/node_modules/electron-edge-js
> node tools/install.js

  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clrfunc.o
../src/mono/clrfunc.cpp:293:17: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                result->Set(
                ^~~~~~~~~~~
../src/mono/clrfunc.cpp:314:17: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                result->Set(Nan::GetCurrentContext(), i, ClrFunc::MarshalCLRToV8(value, exc));
                ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/mono/clrfunc.cpp:378:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    result->SetPrototype(Nan::GetCurrentContext(), v8::Exception::Error(message));
    ^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/mono/clrfunc.cpp:379:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    result->Set(Nan::GetCurrentContext(), Nan::New<v8::String>("message").ToLocalChecked(), message);
    ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/mono/clrfunc.cpp:382:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    result->Set(Nan::GetCurrentContext(), Nan::New<v8::String>("name").ToLocalChecked(), name);
    ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/mono/clrfunc.cpp:421:13: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
            result->Set(
            ^~~~~~~~~~~
../src/mono/clrfunc.cpp:448:17: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                result->Set(
                ^~~~~~~~~~~
7 warnings generated.
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clrfuncinvokecontext.o
../src/mono/clrfuncinvokecontext.cpp:19:28: warning: unused variable 'context' [-Wunused-variable]
    v8::Local<v8::Context> context = isolate->GetCurrentContext();
                           ^
1 warning generated.
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/monoembedding.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/task.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/dictionary.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/nodejsfunc.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/nodejsfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/utils.o
  CXX(target) Release/obj.target/edge_nativeclr/src/common/utils.o
../src/common/utils.cpp:24:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        exception->SetPrototype(Nan::GetCurrentContext(), v8::Exception::Error(Nan::New<v8::String>(message).ToLocalChecked()));
        ^~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  CXX(target) Release/obj.target/edge_nativeclr/src/common/v8synchronizationcontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/common/callbackhelper.o
  CXX(target) Release/obj.target/edge_nativeclr/src/common/edge.o
  SOLINK_MODULE(target) Release/edge_nativeclr.node
  CXX(target) Release/obj.target/edge_coreclr/src/common/v8synchronizationcontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/callbackhelper.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/edge.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrembedding.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrfunc.o
../src/CoreCLREmbedding/coreclrfunc.cpp:474:4: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                        result->Set(Nan::GetCurrentContext(), i, MarshalCLRToV8(arrayData->itemValues[i], arrayData->itemTypes[i]));
                        ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/CoreCLREmbedding/coreclrfunc.cpp:487:4: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                        result->Set(Nan::GetCurrentContext(), Nan::New<v8::String>(objectData->propertyNames[i]).ToLocalChecked(), MarshalCLRToV8(objectData->propertyData[i], objectData->propertyTypes[i]));
                        ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/CoreCLREmbedding/coreclrfunc.cpp:495:4: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                        result->SetPrototype(Nan::GetCurrentContext(), v8::Exception::Error(message));
                        ^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/CoreCLREmbedding/coreclrfunc.cpp:496:4: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                        result->Set(Nan::GetCurrentContext(), Nan::New<v8::String>("message").ToLocalChecked(), message);
                        ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/CoreCLREmbedding/coreclrfunc.cpp:497:4: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                        result->Set(Nan::GetCurrentContext(), Nan::New<v8::String>("name").ToLocalChecked(), name);
                        ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5 warnings generated.
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrnodejsfunc.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrnodejsfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/utils.o
../src/common/utils.cpp:24:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        exception->SetPrototype(Nan::GetCurrentContext(), v8::Exception::Error(Nan::New<v8::String>(message).ToLocalChecked()));
        ^~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/pal/pal_utils.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/pal/trace.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/fxr/fx_ver.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/fxr/fx_muxer.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/json/json.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/json/json_parsing.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/json/json_serialization.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/utilities/asyncrt_utils.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/deps/deps_format.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/deps/deps_entry.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/deps/deps_resolver.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/args.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/coreclr.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/libhost.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/runtime_config.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/pal/pal.unix.o
  SOLINK_MODULE(target) Release/edge_coreclr.node
  ACTION binding_gyp_build_managed_target_restore_bootstrap_packages lib/bootstrap/project.lock.json
  Determining projects to restore...
  Restored /Users/Mac_User_Name/Projects/GitHub/Project_Folder/node_modules/electron-edge-js/lib/bootstrap/bootstrap.csproj (in 1.18 sec).
  Restored /Users/Mac_User_Name/Projects/GitHub/Project_Folder/node_modules/electron-edge-js/src/double/Edge.js/Edge.js.csproj (in 1.21 sec).
  ACTION binding_gyp_build_managed_target_compile_bootstrap lib/bootstrap/bin/Release/netcoreapp1.1/bootstrap.dll
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Edge.js -> /Users/Mac_User_Name/Projects/GitHub/Project_Folder/node_modules/electron-edge-js/src/double/Edge.js/bin/Release/netcoreapp1.1/EdgeJs.dll
  bootstrap -> /Users/Mac_User_Name/Projects/GitHub/Project_Folder/node_modules/electron-edge-js/lib/bootstrap/bin/Release/netcoreapp1.1/bootstrap.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.85
  ACTION binding_gyp_build_managed_target_compile_mono_embed build/Release/monoembedding.exe
  TOUCH Release/obj.target/build_managed.stamp
+ electron-edge-js@12.14.2
added 253 packages from 178 contributors and audited 254 packages in 50.043s
found 0 vulnerabilities

Mac_User_Name@Macbook Project_Folder % 

```

Error from npm package

```
Error: The module '/Users/Mac_User_Name/Projects/GitHub/Project_Folder/node_modules/electron-edge-js/build/Release/edge_nativeclr.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
	at process.func (electron/js2c/asar.js:140:31)
	at process.func [as dlopen] (electron/js2c/asar.js:140:31)
	at Object.<anonymous> (internal/modules/cjs/loader.js:969:18)
	at Object.func (electron/js2c/asar.js:140:31)
	at Object.func [as .node] (electron/js2c/asar.js:140:31)
	at Module.load (internal/modules/cjs/loader.js:782:32)
	at internal/modules/cjs/loader.js:695:12
	at electron/js2c/asar.js:717:26
	at Function.<anonymous> (electron/js2c/asar.js:717:26)
	at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
	at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
	at Function._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:971:844)
	at Module.require (internal/modules/cjs/loader.js:822:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:135)
	at Object.<anonymous> (/Users/Mac_User_Name/Projects/GitHub/Project_Folder/node_modules/electron-edge-js/lib/edge.js:64:10)
	at Module._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:360)
	at Object..js (internal/modules/cjs/loader.js:939:10)
	at Module.load (internal/modules/cjs/loader.js:782:32)
	at internal/modules/cjs/loader.js:695:12
	at electron/js2c/asar.js:717:26
	at Function.<anonymous> (electron/js2c/asar.js:717:26)
	at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
	at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
	at Function._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:971:844)
	at Module.require (internal/modules/cjs/loader.js:822:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:135)
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:61:32
	at Generator.next (<anonymous>)
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:8:71
	at new Promise (<anonymous>)
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:4:12
	at format (/Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:43:12)
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:26:27
	at Generator.next (<anonymous>)
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:8:71
	at new Promise (<anonymous>)
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:4:12
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:23:30
	at Object._withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:672)
	at Object.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:426)
	at Object.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:944:395)
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:19:33
	at Generator.next (<anonymous>)
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:8:71
	at new Promise (<anonymous>)
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:4:12
	at /Users/Mac_User_Name/Projects/GitHub/Project_Folder/out/extension.js:17:107
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:937:271
	at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:598:242)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:937:260
	at _executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:374)
	at _.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:749)
	at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:926)
	at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:618)
	at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:818:252)
	at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:817:6)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:815:161
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:494)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1007:179
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:494)
	at Object._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:244:17)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:67
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:949)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:301
	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:245:572)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by sammosampson** [comment]
Any updates?

**Comment by pmahend1** [comment]
I was able to get rid of this error. I think I removed the system level nodejs which was latest and installed LTS version.
